function(edge_sentinel_enable_sanitizers target_name)
    if(MSVC)
        if(EDGE_SENTINEL_ENABLE_TSAN OR EDGE_SENTINEL_ENABLE_UBSAN)
            message(FATAL_ERROR "TSan and UBSan presets are supported on Linux GCC/Clang only")
        endif()
        if(EDGE_SENTINEL_ENABLE_ASAN)
            target_compile_options(${target_name} PRIVATE /fsanitize=address)
            target_link_options(${target_name} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()

    if(EDGE_SENTINEL_ENABLE_TSAN AND (EDGE_SENTINEL_ENABLE_ASAN OR EDGE_SENTINEL_ENABLE_UBSAN))
        message(FATAL_ERROR "ThreadSanitizer must run in a separate build from ASan/UBSan")
    endif()

    set(sanitizers "")
    if(EDGE_SENTINEL_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(EDGE_SENTINEL_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()
    if(EDGE_SENTINEL_ENABLE_TSAN)
        list(APPEND sanitizers "thread")
    endif()

    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_list)
        target_compile_options(${target_name} PRIVATE -fsanitize=${sanitizer_list} -fno-omit-frame-pointer)
        target_link_options(${target_name} PRIVATE -fsanitize=${sanitizer_list})
    endif()
endfunction()
